### ISSUE TITLE
 im noob ..error

### ISSUE THREAD

**Issue by cheese0307** [zkemble/NWatch#5]
C:\Users\ADMINI~1\AppData\Local\Temp\cc9zl9qr.ltrans0.ltrans.o: In function `oled_flush':

C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:108: undefined reference to `spi_transfer_nr'

C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:109: undefined reference to `spi_transfer_nr'

C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:110: undefined reference to `spi_transfer_nr'

C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:112: undefined reference to `spi_transfer_nr'

C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:113: undefined reference to `spi_transfer_nr'

C:\Users\ADMINI~1\AppData\Local\Temp\cc9zl9qr.ltrans0.ltrans.o:C:\Users\ADMINI~1\AppData\Local\Temp\arduino_build_31448\sketch/oled.c:114: more undefined references to `spi_transfer_nr' follow

collect2.exe: error: ld returned 1 exit status

exit status 1
为开发板 Arduino Leonardo 编译时出错。

**Comment by ZakKemble** [comment]
N|Watch is not an Arduino compatible project. You need to use [Atmel Studio](https://www.microchip.com/mplab/avr-support/atmel-studio-7).
