### ISSUE TITLE
Fuses for ATmega328/328P

### ISSUE THREAD

**Issue by 7918514** [zkemble/NWatch#7]
You have fuses:
High: 0xDE
Low: 0xE2
Extended: 0x06
This is right? These fuses are for external quartz.

**Comment by ZakKemble** [comment]
No, they're correct. I think you have got the high and low fuses mixed up.

**Comment by 7918514** [comment]
I beg your pardon. You're right. I looked carelessly. I'm used to Low, High, Extended.
Thanks!
